// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp34O5LbiC7vABKFzdU21a6YxKPmu83Ic',
    appId: '1:758304835285:web:6bc23cfaec2725d661845c',
    messagingSenderId: '758304835285',
    projectId: 'brainsprint-bf985',
    authDomain: 'brainsprint-bf985.firebaseapp.com',
    storageBucket: 'brainsprint-bf985.firebasestorage.app',
    measurementId: 'G-9TDY5RNYQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWqC35z49WbNHr4miLB7Cpf5SAEHU66fw',
    appId: '1:758304835285:android:8356ab99ed0aef4061845c',
    messagingSenderId: '758304835285',
    projectId: 'brainsprint-bf985',
    storageBucket: 'brainsprint-bf985.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVCY-gVs24gAdKGGkconVPvI6c3BN_SUo',
    appId: '1:758304835285:ios:f9944da35dacb96961845c',
    messagingSenderId: '758304835285',
    projectId: 'brainsprint-bf985',
    storageBucket: 'brainsprint-bf985.firebasestorage.app',
    iosBundleId: 'com.example.brainsprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVCY-gVs24gAdKGGkconVPvI6c3BN_SUo',
    appId: '1:758304835285:ios:f9944da35dacb96961845c',
    messagingSenderId: '758304835285',
    projectId: 'brainsprint-bf985',
    storageBucket: 'brainsprint-bf985.firebasestorage.app',
    iosBundleId: 'com.example.brainsprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp34O5LbiC7vABKFzdU21a6YxKPmu83Ic',
    appId: '1:758304835285:web:47560e03d18f196461845c',
    messagingSenderId: '758304835285',
    projectId: 'brainsprint-bf985',
    authDomain: 'brainsprint-bf985.firebaseapp.com',
    storageBucket: 'brainsprint-bf985.firebasestorage.app',
    measurementId: 'G-QT1CDC0VXR',
  );

}